version: '2.1'
services:
  db:
    image: microsoft/mssql-server-windows-express:2016-sp1
    environment:
      sa_password: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433" # REMARK: This is currently required, needs investigation
    healthcheck:
      test: [ "CMD", "sqlcmd", "-U", "sa", "-P", "${SA_PASSWORD}", "-Q", "select 1" ]
      interval: 10s
      retries: 10
  octopus:
    image: octopusdeploy/octopusdeploy:4.1.4
    environment:
      OctopusAdminUsername: "${OCTOPUS_ADMIN_USERNAME}"
      OctopusAdminPassword: "${OCTOPUS_ADMIN_PASSWORD}"
      sqlDbConnectionString: "Server=db,1433;Initial Catalog=Octopus;Persist Security Info=False;User ID=sa;Password=${SA_PASSWORD};MultipleActiveResultSets=False;Connection Timeout=30;"
    ports:
     - "81"
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true #Process sits and waits for ReadLine
    volumes:
      - "../tests/Import:C:/Import"
      #- "../tests/Repository:C:/Repository"
  tentacle:
    image: alantsai/octopus-tentacle:3.16.3-aspnet_4.7.1_windowsservercore_ltsc2016
    depends_on:
      octopus:
        condition: service_healthy
    environment:
      ServerUsername: "${OCTOPUS_ADMIN_USERNAME}"
      ServerPassword: "${OCTOPUS_ADMIN_PASSWORD}"
      TargetEnvironment: "Development"
      TargetRole: "app-server"
      ServerUrl: "http://octopus:81"
    stdin_open: true #Process sits and waits for ReadLine
    #volumes:
      #- "../tests/Applications:C:/Applications"
networks:
  default:
    external:
      name: nat
